### ISSUE TITLE
Python version is wrong

### ISSUE THREAD

**Issue by DerRudi074** [incmve/Autosub-qnap#2]
Since the updates to firmware 4.x python 2.6 no longer exists on Qnap devices. I changed it to 2.7 and it works like a charm.

For single disk qnap's the right location for the folders is:
/share/HDA_DATA/.qpkg/

That's it. Thanks for putting this online helped me a lot!

Cheers, Rudi.

**Comment by incmve** [comment]
Hi, I am not using it anymore.
I use Sickrage to download tv shows and Sickrage can also search subtitels.
Now I just use Kodi with a subtitel plugin.

But nice to hear it helped someone :)
